girlbossceo/conduwuit

conduit-example.toml, src/api/client_server/account.rs, src/config/mod.rs, src/service/globals/mod.rs
User reported in upstream Conduit that if you selfhost Element with guest access enabled and your default homeserver is Conduit, the *first* user or bot that visits that Element will automatically register a guest account via `/_matrix/client/v3/register?kind=guest` POST and a JSON body of simply the initial device display name; even if you have registration disabled with or without token registration.
Element sends `/_matrix/client/v3/register?kind=guest` automatically, but *any* Matrix homeserver running Conduit is vulnerable to *anyone* sending a POST request with URI `/_matrix/client/v3/register?kind=guest` and a JSON body with `initial_device_display_name` and it will create a guest account. There are definitely spambots doing this.
Conduit does not check if the first user is a guest …
=> Various guest user registration stuff and related logging

Cargo.lock, Cargo.toml, DIFFERENCES.md, src/api/client_server/sync.rs, src/api/client_server/unversioned.rs, src/api/server_server.rs, src/config/mod.rs, src/main.rs, src/service/globals/mod.rs, src/service/pusher/mod.rs, src/service/rooms/state_accessor/mod.rs
Bump ruma to latest commit, ability to serve client/server well-knowns from conduwuit, ability to server `/client/server.json` from conduwuit which is just a sliding sync proxy non-standard health check endpoint that Element Web uses, declare support for some Matrix versions that we should have been declaring (compared ours with Dendrite and Synapse just to be safe), and send a User-Agent on all of our requests which Conduit impressively was not doing this entire time.
=> More misc things

DIFFERENCES.md, src/api/client_server/media.rs, src/api/client_server/message.rs, src/api/server_server.rs, src/config/mod.rs, src/service/globals/mod.rs, src/service/rooms/timeline/mod.rs
Solves https://github.com/girlbossceo/conduwuit/issues/98 and https://github.com/girlbossceo/conduwuit/issues/100
As usual, the denial of service was just dumb unwrapping/expecting. Replacing it with a proper error would prevent crashing, who would have known? Do I look crazy for wanting to return proper errors instead of panicking and unwrapping everything or something?
Also adds support for blocking servers from fetching remote media from. Config option is `prevent_media_downloads_from = ["server.name1", "server.name2"]`
Technically you can add yourself into it, but it would be a no-op as there's code that prevents sending federation requests to ourselves (assuming that isn't broken), and a check if the requested media belongs to our server before we try fetching over federation. Don't …
=> 17 01 2023

.github/workflows/ci.yml
Fix nodejs v16 incompatible/deprecation
Per recommended usage: https://github.com/DeterminateSystems/magic-nix-cache-action#usage
=> bump nix cache

.github/workflows/ci.yml, .gitlab-ci.yml, Cargo.lock, Cargo.toml, DEPLOY.md, DIFFERENCES.md, bin/complement, bin/nix-build-and-cache, complement/Dockerfile, complement/README.md, debian/README.md, debian/postinst, flake.lock, flake.nix, src/database/mod.rs
- Builds static x86 and aarch64 Linux musl binaries
- Builds x86 and aarch64 OCI images for Docker
- Builds x86 deb file (no aarch64 until upstream has it)
Also merges the rest of some upstream changes related to GitLab CI so we could copy.
=> GitHub Actions CI port

docker/README.md
Fixes 2 broken links in the docker documentation.
=> docs: Fix 2 Links To Config Example

src/api/client_server/profile.rs, src/api/client_server/sync.rs, src/database/key_value/presence.rs, src/database/mod.rs
Instead of checking if we should update every time we want to update, call the updater every time and decide internally.
=> Reduce number of separate sources of truth for presence disabled-ness

flake.nix
=> dont include the timestamp in the docker image created date

flake.nix
dockerhub and github container registry don't like this, and i have no idea what to do.
=> remove created date from OCI image generation

.github/workflows/ci.yml
test -n checks if a string is longer than non-zero, but we just need a compare
=> Remove extra test flag when publishing to ghcr in the CI

.github/workflows/ci.yml
Artifacts were being created with various names depending on whether they were renamed before uploading, I've attempted to standardise the names and rename all artifacts prior to upload.
This will hopefully make the Docker manifest creation simpler to maintain in the future, as it's being created/named exactly the same way as the other artifact types.
_Edit: After discussion in the Conduwuit room, I've turned off artifact building in PRs, so builds will undergo the suite of CI tests (and update the Nix cache) but should complete in under 10 minutes._
_Builds can be requested manually through the GitHub Actions UI, but as more testing is being done through the Dev branch, it makes sense to get PRs approved faster into the Dev branch, then build artifacts there to get people testing them …
=> Improved CI artifact filename handling

.github/workflows/ci.yml
All images should be generating correctly with parallelism and Docker manifests, and should output the end of the CI testing errors in a job summary box when the test fails.
When the test succeeds you get a big ✅ then at the end of the Docker publish it should include the `docker pull` commands for both Docker Hub and GHCR registries to make those pesky Docker users lives easier!
=> CI working with job summaries

Cargo.lock, Cargo.toml, docs/development.md, src/database/mod.rs, src/main.rs, src/service/admin/debug/debug_commands.rs, src/service/globals/mod.rs, src/service/mod.rs
@girlbossceo you may want to copy [my tracing branch](https://github.com/Benjamin-L/tracing/tree/tracing-subscriber/env-filter-clone-0.1.x-backport) into your github account to match the other git dependencies. The tracing change that we need is https://github.com/tokio-rs/tracing/pull/2956. I made this PR against the master branch, and don't know how likely it is that it will be backported to the 0.1.x branch by upstream tracing. If not, we might be maintaining the fork for a long time. If we don't want to do this, there are alternative ways to get the `LogLevelReloadHandles` wrapper to work, but they are ugly.
The refactor of how the reload handle works also enables fixing the current behavior where enabling `allow_jaeger` or `tracing_flame` will disable the normal (and sentry) logging, …
=> add optional support for tokio-console

conduwuit-example.toml, src/config/mod.rs, src/main.rs
Bugs fixed:
- enabling tracing-flame would disable normal logging
- tracing-flame IO buffers were not flushed on exit
- when tracing-flame was enabled, changing the log level at runtime with the admin interface would modify the tracing-flame filter instead of the log level (which didn't exist because it wasn't logging anything on stdout)
I also added a couple options to make tracing_flame that were necessary to use tracing-flame on our HS.
The refactoring that fixed the first bug (stdout logging being disabled) also fixed a similar bug for jaeger. Even after this fix, jaeger is still not working because we're initializing it outside of the tokio context. If you try to run conduwuit with `allow_jaeger = true`, it will panic. We discussed removing jaeger support instead of fixing it in the …
=> Fix tracing-flame bugs and add some config options

nix/pkgs/main/default.nix
Currently, trying to use conduwuit with Nix without flakes (using the `default.nix` which uses flake-compat) fails because the `CONDUWUIT_EXTRA_VERSION` env var is set using values from `inputs.self`. flake-compat doesn't provide `self` in inputs, just the actual inputs, so this change falls back to an empty string if `inputs.self` isn't available.
=> fix extra version when using flake-compat

src/api/client_server/alias.rs
Only normal users should be prevented from creating an alias within an exclusive namespace, not the appservice itself. This mirrors the behaviour in `api/client_server/room.rs` on room creation.
=> Fix appservice namespace check for room aliases

Cargo.lock, Cargo.toml, src/api/client_server/media.rs, src/router/mod.rs, src/utils/content_disposition.rs, src/utils/mod.rs
These are follow up security enhancements from the previous security release.
Adds various recommended security response HTTP headers if not present already, including a strong Content-Security-Policy, as recommended by [spec](https://spec.matrix.org/v1.10/client-server-api/#security-considerations-4) and every websec guide out there. This has no affect on clients as it's only affecting the content being loaded, not what's loading the content. Malicious inline content has substantially less risk now. All of Matrix is just a bunch of JSON anyways so we shouldn't allow things like JavaScript execution/loading or frame ancestors anywhere.
Attempt to identify the Content-Type / MIME type from the file being uploaded via the file contents magic signatures and return `inline` …
=> Media security enhancements

src/api/client_server/membership.rs
This reverts commit 321a6ca0fefccc87b334d7410aba18c512fcee2b.
These checks were not working as intended, resulting in the unban button not working
The join check gets kept since it slightly reduces the amount of sent joins in some cases This check will probably be replaced soon for a more universal solution to the "made no change" issue
=> Revert "feat(membership): check if user already has the membership that is requested to be set"

src/api/client_server/sync.rs, src/service/globals/mod.rs
This cache can serve invalid responses, and has an extremely low hit rate.
It serves invalid responses because because it's only keyed off the `since` parameter, but many of the other request parameters also affect the response or it's side effects. This will become worse once we implement filtering, because there will be a wider space of parameters with different responses. This problem is fixable, but not worth it because of the low hit rate.
The low hit rate is because normal clients will always issue the next sync request with `since` set to the `prev_batch` value of the previous response. The only time we expect to see multiple requests with the same `since` is when the response is empty, but we don't cache empty responses.
This was confirmed experimentally by logging cache hits and …
=> remove sync response cache

src/api/client_server/sync.rs
Previously, we were returning redundant member count updates or encrypted device updates from the /sync endpoint in some cases. The extra member count updates are spec-compliant, but unnecessary, while the extra encrypted device updates violate the spec.
The refactor necessary to fix this bug is also necessary to support filtering on state events in sync.
Joined room incremental sync needs to examine state events for four purposes:
1. determining whether we need to return an update to room member counts
2. determining the set of left/joined devices for encrypted rooms (returned in `device_lists`)
3. returning state events to the client (in `rooms.joined.*.state`)
4. tracking which member events we have sent to the client, so they can be omitted on future requests when lazy-loading is …
=> Bugfix: don't return extra member count or e2ee device updates from sync

.envrc, .github/workflows/ci.yml, bin/complement, bin/nix-build-and-cache, flake.nix, nix/pkgs/main/default.nix
This should hopefully resolve the "invalid free" error in CI for #392, and may resolve the segfault in #346.
This makes the following changes:
- only link one instance of jemalloc
- perform default-features unification in nix instead of cargo (this is more general version of what [this](https://github.com/girlbossceo/conduwuit/pull/392/commits/e61c7d24b2bf4a1f00dee0a39d52dca69467132b#diff-b4b08231ad4154725ea223e7749071af5d05f5b2844f0ff1057164045dc48269R22) and [this](https://github.com/girlbossceo/conduwuit/pull/346/files#diff-b4b08231ad4154725ea223e7749071af5d05f5b2844f0ff1057164045dc48269R27) are doing)
- use static linking in the devshell (and therefore for unit tests in CI)
- run CI with an all-features devshell
This does _not_ fix the issue that dynamically-linked jemalloc builds …
=> fix jemalloc linking in CI

debian/postinst
This check is needed because the binary fails to install completely, if symlink is already existing
**test -L $object** [object exists and is a symbolic link (same as -h)]
It is not recommended to use -h [Excerpt: True if file exists and is a symbolic link. This operator is retained for compatibility with previous versions of this program. Do not rely on its existence; use -L instead.]
=> Check if database symlink already exists

src/admin/media/media_commands.rs, src/admin/media/mod.rs, src/service/media/mod.rs
When enabled, if a file is deemed unremovable, it skips past it and continues deleting all other files that fit the criteria. Additionally, fix age comparison under the same command.
=> admin: media: Force flag on past media removal

src/service/globals/migrations.rs, src/service/rooms/state_cache/data.rs, src/service/rooms/state_cache/mod.rs, tests/test_results/complement/test_results.jsonl
Follow up conduwuit-specific one-time migration fixing bad data from fixing `fix_bad_double_separator_in_state_cache`
Users may need to clear client cache for the fixes to be fully apparent.
=> retroactively fix bad data in `roomuserid_joined`, remove pointless prefix scans

debian/README.md, docs/SUMMARY.md, docs/configuration.md, docs/configuration/examples.md, docs/deploying/docker.md, docs/deploying/generic.md, docs/maintenance.md, docs/troubleshooting.md, docs/turn.md
This adds a spot in the configuration chapter that explains how the app can be configured.
The goal here was to make it a bit more clear how the app can be configured.
When I was launching this app from a container I needed to look around to figure out how to specify the config file to use and found the `CONDUWUIT_CONFIG` variable listed in some other files which clued me into how the settings were being set.
=> Improve configuration documentation

debian/postinst
Related: https://github.com/girlbossceo/conduwuit/issues/465
When getting this app deployed I was running into confusion about which environment variables were needed. During that process I noticed that this variable is not used in the postinst script, so I removed it to help reduce the confusion.
- remove unused CONDUWUIT_CONFIG_FILE variable from debian postinst script
=> remove unused CONDUWUIT_CONFIG_FILE variable

arch/conduwuit.service
The previous migration may bring trouble if users ignore the post upgrade message and don’t change their database_path after upgrading. This bind mount property should make things better.
=>  Bind Mount the old matrix-conduit directory

src/service/sending/sender.rs
I run a homeserver whose logs show a high number of incoming empty presence EDUs originating from the user agent "Conduwuit/0.4.4". They arrive at a rate of about 2 queries per second per Conduwuit server.
The empty EDUs all look the same, only with `origin_server_ts` increasing:
```
{"origin":"example.com","origin_server_ts":1720266475601,"edus":[{"edu_type":"m.presence","content":{"push":[]}}]}
```
These updates are unnecessary because they don't do anything. They only increase network traffic and CPU usage on both sides.
After this commit, the empty presence updates are no longer inserted into the outgoing event queue.
=> Don't send empty presence EDUs

docs/deploying/docker-compose.with-caddy.yml, docs/deploying/docker.md
As discussed on Matrix, I've added a compose setup which uses `caddy-docker-proxy` as the reverse proxy. After replacing `example.com` with a real domain and pointing DNS A records to the correct IP, this setup should work out of the box.
=> Documentation: Introduce a new way of deploying conduwuit using caddy in Docker

conduwuit-example.toml, nix/pkgs/complement/config.toml
`migrations.rs` refers to `startup` instead of `statup`. ~~There is currently no warning if an invalid config variable is set, as far as I can tell.~~
https://github.com/girlbossceo/conduwuit/blob/06531993f69b8cefd5d67d3589791ca9cd6785c2/src/service/globals/migrations.rs#L130
Briefly tested with the `CONDUWUIT_MEDIA_STARTUP_CHECK=true` environment variable in the latest docker image, but not main or Complement. Can do so if necessary, but the change seems simple enough. I checked for other misspellings in `conduwuit-example.toml` and didn't find any, but I'm not familiar with the codebase, yet, so I may have missed others.
=> fix media_startup_check typo

.gitea/workflows/ci.yml
ci: typo, steps name is Sync repository 
format {org}/{repo}[/path]@ref. Actual 'https://github.com/https://github.com/actions/checkout@v4' 
-----------------------------------------------------------------------------
=> ci: typo, steps name is Sync repository

docs/conduwuit_coc.md
while their code of conduct has very great baseline points, this is not a code of conduct the foundation upholds themselves, so it would be a disservice to mislead folks into using this as a baseline.
=> remove matrix.org code of conduct from conduwuit's foundational rules

docs/deploying/generic.md
journald itself (when viewed through journalctl) omits conduwuit’s ANSI escape code, but rsyslog displays either colour or `#033` strings:
https://www.rsyslog.com/doc/configuration/input_directives/rsconf1_escapecontrolcharactersonreceive.html
https://access.redhat.com/solutions/1484553
=> Add config note for systems that pass on journal to rsyslog

docs/deploying/generic.md
I assume the suggestion of `proxy_buffering off;` was prompted by a warning such as `an upstream response is buffered to a temporary file` because the image file exceeds the (8 4k|8k) in-memory buffer size. In which case the user should probably increase the default buffer size in the first instance (if there’s enough RAM) rather than turning off buffering to suppress the warning. I’m linking to Vershinin‘s article because it seems to be the most thorough one on this subject.
`adduser` is a symlink to `useradd` on recent Fedora/RHEL and doesn’t accept the same flags as Debian so I propose removing them from that paragraph.
=> improve some general documentation

conduwuit-example.toml, src/core/config/mod.rs, src/service/client/mod.rs
This is helpful to, for example, bind to an interface that can only access the public internet. The resulting setup is less maintenance-heavy / error-prone than manually maintaining a deny/allowlist to protect internal resources.
In my setup, I'm using podman's `macvlan` driver to provide direct access to my host's `eno1` interface, which accesses the public net, like so:
```unit
[Network]
DisableDNS=false
IPv6=true
Subnet=10.89.1.0/24
Gateway=10.89.1.1
Driver=macvlan
Options=parent=eno1
```
This means that the URL preview requests can't access any of my local services or my private network.
=> add support for binding to a specific interface for url previews

.github/workflows/ci.yml
This commit contains two separate fixes:
1) use lowercased github username/repository for the docker repository name. 
This is because image registries only accept lowercase in image repository names, but github stores the repository and username in a case-sensitive manner. This broke image uploads for me, as my username has uppercase chars.
2) change run conditions for some steps.
It will no longer attempt to set up SSH web publishing if the SSH private key is not set.
It will also run the image registry upload steps if registry usernames are missing, instead skipping individual uploads where the token for that registry is missing.
Finally, it simplifies the sccache run conditions to use the `SCCACHE_GHA_ENABLED` env variable, rather than duplicating that logic.
=> fix github actions runs on forks

src/admin/media/mod.rs
As mentioned in the offtopic Matrix room, the documentation for this command continues to be confusing to some people (myself included) and these proposed changes merely alter the description of the command, and document what the before and after arguments actually do, to remove any ambiguity.
Open to suggestions for improvements, but this is pretty clear to me.
=> Improve documentation for `delete-past-remote-media` admin command

clippy.toml, conduwuit-example.toml, src/core/config/mod.rs
Although the configuration file was mostly wrapped to a line-width of 80, some lines were wrapped slightly shorter. I fixed this.
In general, all sentences were changed to start with a capital letter and end with a period or other punctuation mark.
Many of the documentation commets read as, "config option to do XYZ". I shortened these to simply "do XYZ".
=> Improve documentation for configuration

src/api/client/sync/v3.rs
This is a relatively simple fix, but it should significantly increase performance for syncv3 clients.
=> automatically retry returning data in syncv3

Cargo.lock, Cargo.toml, conduwuit-example.toml, src/api/Cargo.toml, src/api/client/capabilities.rs, src/api/client/session.rs, src/api/router.rs, src/core/config/mod.rs, src/database/maps.rs, src/service/Cargo.toml, src/service/globals/mod.rs, src/service/users/mod.rs
This is a component of QR login without OIDC. (the other one being the insecure rendezvous endpoint for encryption, also used for OIDC QR login)
It allows existing sessions to generate short-lived tokens which can be used to login a new session. Tokens are automatically deleted on use.
I've added two new config options, one allowing disabling the generation and usage of the tokens and the other setting the length the tokens are valid for (by default two minutes). For some reason, the example config isn't regenerating, though.
Calling the `/login/get_token` endpoint requires UIA. I've not been able to work out how to reject UIA sessions that have been used before (a security feature required by the spec). This might require storing additional state in the database.
I've also removed the …
=> Implement `/login/get_token`

.github/workflows/docker-hub-description.yml
Adds a github action to push the README to docker.io automatically.
Only runs on the main branch, when the README or workflow change.
=> Publish README to docker hub

.github/workflows/ci.yml, nix/pkgs/oci-image/default.nix
- Uploads haswell images to GHA and then respective registries, like other images
- Breaks the image name stuff into parts, to reduce repetition
- Adds some labels to the OCI image (still missing: description, URL, source, documentation, authors, licenses. See [OCI spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md))
Untested for now, as it seems `https://attic.kennel.juneis.dog` is having issues, failing the build.
=> Publish haswell images to image registries

.gitattributes
.gitattributes is explained at https://git-scm.com/book/ms/v2/Customizing-Git-Git-Attributes
But basically windows sometimes will randomly mess with newlines in already created files which creates 'ghost' changes. AKA changes where just the only difference is replacing LN with CRLF. This does not change any rust code and is relatively minor.
=> Adds .gitattributes to the projects to prevent LN and CLRF conflicts.

docs/deploying/generic.md
If the reverse_proxy directive is omitted before 127.0.0.1:6167 in your Caddyfile, enabling the service with systemctl enable will result in an error.
=> Fix in caddyfile guide

src/service/uiaa/mod.rs, tests/test_results/complement/test_results.jsonl
There's probably a cleaner way to do this. ruma's `ErrorKind::forbidden()` actually responds with HTTP 401, but the test expects a 403 response.
=> guard against using someone else's access token in UIAA

src/api/client/space.rs, tests/test_results/complement/test_results.jsonl
This PR fixes requests to `/_matrix/client/v1/rooms/<id>/hierarchy?max_depth=1` only returning the space with the provided ID, excluding its children and causing Element and Cinny to claim the space is empty.
=> Fix off-by-one error in room hierarchy endpoint
