Cargo.lock
Cargo.toml
flake.nix

Someone fix nix bindings or something

bump rust-rockdb to latest git for 8.9.1

---

Cargo.lock
Cargo.toml
src/main.rs

update opentelemetry things

---

.envrc

Cherry-picked from https://gitlab.com/famedly/conduit/-/merge_requests/566

add shebang to .envrc

---

Cargo.lock
Cargo.toml
src/api/client_server/session.rs
src/database/mod.rs
src/lib.rs
src/service/globals/mod.rs
src/service/mod.rs
src/service/uiaa/mod.rs
src/utils/mod.rs

fixes: https://github.com/girlbossceo/conduwuit/issues/22

feat: replaced flaky argon2 with better argon2 crate

---

src/api/client_server/room.rs
src/api/server_server.rs
src/service/admin/mod.rs
src/service/rooms/timeline/mod.rs

Sad that we're panicking over an invalid room version, but oh well hopefully that can get changed by us.
That send_join pubkey fix commit might fix some room join issues.

Update some of our merged upstream MRs

---

DIFFERENCES.md
README.md

Solves https://github.com/girlbossceo/conduwuit/issues/6

Revamp README.md and add our changes from upstream (DIFFERENCES.md)

---

.github/workflows/ci.yml

remove test branch from CI

---

.github/workflows/ci.yml
.gitlab-ci.yml
engage.toml

add cargo audit as engage task

---

Cargo.toml
DEPLOY.md
DIFFERENCES.md
nix/README.md
src/api/client_server/sync.rs
src/api/server_server.rs
src/database/abstraction/rocksdb.rs
src/database/key_value/rooms/search.rs
src/database/key_value/rooms/state.rs
src/database/key_value/rooms/timeline.rs
src/service/admin/mod.rs
src/service/rooms/event_handler/mod.rs
src/service/rooms/search/mod.rs
src/service/rooms/timeline/mod.rs

Fixes federated room v11 redactions (this code could definitely be simplified somewhere) and merges the upstream changes

27 02 2024

---

Cargo.lock
Cargo.toml
src/service/admin/mod.rs
src/service/presence/mod.rs
src/service/sending/mod.rs

Replaced all tokio channel usage I could find with loole as stated in https://github.com/girlbossceo/conduwuit/issues/30, some errors are ignored and testing is still needed.

replace tokio channels with loole

---

.github/workflows/ci.yml

I haven't tested this action, but it's roughly the design I've used in another project... intention is to just strip down the tag suffix quickly with variables at the start, so then you only need one set of docker commands underneath.

Combined publish to Docker container registries

---

.github/workflows/ci.yml

My test hasn't run yet, so there's every chance these changes haven't fixed it, but it's not any more broken than what currently lives in the dev branch, so I'd recommend trying this, otherwise revert to the main branch's ci.yml to at least get a full release out and I'll ask a friend for advice tomorrow 🙂

Simplify docker manifest CI stage

---

src/service/rooms/auth_chain/mod.rs
src/utils/mod.rs

Added some tracing calls to the auth chain walker, as well as a helper for putting unbounded slices in span arguments.

auth_chain debugging

---

Cargo.lock
Cargo.toml
src/utils/content_disposition.rs

This reverts commit 653ec3799e758abbac4d34993a221a0f65a5244c.

Revert "bump various deps"

---

Cargo.lock
Cargo.toml
src/database/rocksdb/kvtree.rs
src/utils/content_disposition.rs

This requires better integration with coroutines, folly, and optimize multi get for I/O, otherwise we end up with broken io_uring for some users (transfem.dev downtime)
https://github.com/facebook/rocksdb/blob/7d9642d8761725cbc02a6bd6e8011a2865ec4d00/db/version_set.cc#L2622-L2623
https://github.com/facebook/rocksdb/wiki/Asynchronous-IO
https://github.com/rust-rocksdb/rust-rocksdb/pull/751#issuecomment-1489251694

Revert rocksdb async io

---

Cargo.lock

(submitted this on their behalf because I am dumb and realised we need this so our CI doesn't fail for the release lol)

bump lockfile

---

src/service/media/mod.rs

aarch64-unknown-linux-musl doesn't have btime, so the `!admin media delete-past-remote-media` command will error out. this commit fixes it
PS. how do i cross compile this to aarch64

add modification time fallback if birth time is not supported on this platform

---

docs/conduwuit_coc.md

- Included brief intro on what Conduwuit is
- Added muting (PL -1) as a potential moderation action
- Confirmed moderators are accessible via DM when required
- Swapped room names with aliases for clarity
- Removed a few redundant words
- Line breaks and whitespace tweaks

Code of Conduct Refinements

---

src/admin/appservice/appservice_command.rs
src/admin/debug/debug_commands.rs
src/admin/debug/mod.rs
src/admin/federation/federation_commands.rs
src/admin/federation/mod.rs
src/admin/media/media_commands.rs
src/admin/query/mod.rs
src/admin/query/room_state_cache.rs
src/admin/room/mod.rs
src/admin/room/room_info_commands.rs
src/admin/room/room_moderation_commands.rs
src/admin/user/mod.rs
src/admin/user/user_commands.rs
src/admin/utils.rs
src/api/client/account.rs
src/api/client/directory.rs
src/api/client/membership.rs
src/api/client/mod.rs
src/api/server/invite.rs
src/api/server/publicrooms.rs
src/api/server/send.rs
src/core/utils/mod.rs
src/router/layers.rs
src/service/rooms/spaces/mod.rs
src/service/rooms/state_accessor/mod.rs

This also has the force room state command. It still could use more improvements, but for general uses it works.

Admin room command improvements, new commands, and log client IP on some requests

---

docs/deploying/docker-compose.for-traefik.yml
docs/deploying/docker-compose.override.yml
docs/deploying/docker-compose.with-caddy.yml
docs/deploying/docker-compose.with-traefik.yml
docs/deploying/docker-compose.yml

As discussed in Matrix. Also, I've removed the deprecated compose version.

Fix CONDUWUIT_CONFIG environment variable in Docker

---

conduwuit-example.toml
src/admin/debug/commands.rs
src/admin/debug/mod.rs
src/core/config/mod.rs
src/database/database.rs
src/database/engine.rs
src/database/map.rs
src/database/maps.rs
src/database/opts.rs

- Add `rocksdb_stats_level` to config file
- Add `!admin debug database-stats` command

Database properties query

---

Cargo.lock
Cargo.toml
conduwuit-example.toml
src/admin/command.rs
src/admin/debug/commands.rs
src/admin/debug/mod.rs
src/admin/handler.rs
src/core/Cargo.toml
src/core/config/mod.rs
src/core/error/mod.rs
src/core/info/mod.rs
src/core/log/capture/data.rs
src/core/log/capture/layer.rs
src/core/log/fmt.rs
src/core/utils/string.rs
src/database/database.rs
src/database/engine.rs
src/database/map.rs
src/database/maps.rs
src/database/opts.rs
src/service/admin/mod.rs

Tracing logs generated from any admin command can be captured and included in the result.

Admin command tracing capture

---

src/service/rooms/pdu_metadata/mod.rs

The two branches of the `match` pattern on `dir` used identical code. I removed the code duplication and reversed the order of the returned `chunk` - looks like we got it backwards the first time around.
Threaded messages load in the correct order in my Element Desktop instance with these changes.

`paginate_relations_with_filter` DRY & flip ordering #504

---

docs/deploying/generic.md

I don't think this works if the commands are invoked on the same line with no thing joining them, so separate them on to separate lines.

Separate command lines

---

src/api/client/room/initial_sync.rs
src/api/client/room/mod.rs
src/api/client/sync/v3.rs
src/api/router.rs
src/database/map/get.rs
src/database/map/insert.rs
src/service/rooms/search/mod.rs
src/service/rooms/state/mod.rs
src/service/rooms/state_accessor/data.rs
src/service/rooms/state_accessor/mod.rs
src/service/rooms/state_compressor/mod.rs
src/service/rooms/timeline/mod.rs
src/service/sending/data.rs
src/service/sending/mod.rs
src/service/sending/sender.rs

also fix some responsiveness issues

local room previews

---

docs/deploying/nixos.md

I _might_ write a NixOS module in the future if I find the motivation but I don't want to promise anything.

docs: add workaround to use unix sockets with the nixos module

---

src/core/utils/string.rs

This was causing tests to fail

Fix typo in test from rename

---

Cargo.lock
Cargo.toml
src/api/client/read_marker.rs
src/api/client/sync/v3.rs
src/api/server/send.rs
src/service/rooms/read_receipt/mod.rs
src/service/rooms/typing/mod.rs
src/service/sending/mod.rs
src/service/sending/sender.rs

Note that this is missing presence events, which theoretically should be sent as a part of this MSC. This isn't an issue in practice, though.

Send read reciept and typing indicator EDUs to appservices with receive_ephemeral

---

src/service/admin/console.rs

When the console is launched, it now prints this message:
conduwuit VERSION admin console
"help" for help, ^D to exit the console, ^\ to stop the server

Add header to console

---

.github/workflows/ci.yml

- revert incorrect swapping of manifest create command
- load from the correct image file
- create manifests for unique image tags, fixing the 'no switch manifest' error

Fix haswell uploads
